enum CommandSignal {
  ARM_CHECK_STATUS,
  ARM_STATUS,
  ARM_CONNECT,
  ARM_CONNECTED,
  ARM_MOVE_TO_POINT,
  ARM_APPLY_TRAJECTORY,
  ARM_CANCEL_TRAJECTORY,
  ARM_CANCELED_TRAJECTORY,
  ARM_DISCONNECT,
  ARM_DISCONNECTED,
  ARM_HOME_SEARCHED,
}
export default CommandSignal;
